---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.js"
  - "**.php"
exclude_paths:
- resource/js/bootstrap-multiselect.js
- resource/js/*min.js
- resource/css/jquery.mCustomScrollbar.css
- resource/fonts/*
- resource/pics/*
- tests/*
