language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
install:
  - composer install --no-dev
before_script:
  - cd tests
  - sh ./init_fuseki.sh
  - cd ..
after_script:
  - pkill -f 'java -Xmx1200M -jar'
  - vendor/bin/test-reporter
addons:
  code_climate:
    repo_token: fb98170a5c7ea9cc2bbab19ff26268335e6a11a4f8267ca935e5e8ff4624886c
