sudo: required
language: php
php:
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
before_install:
  - sudo apt-add-repository -y ppa:webupd8team/java
  - sudo apt-get update -qq
  - sudo apt-get install -y oracle-java8-installer
  - sudo update-java-alternatives -s java-8-oracle
install:
  - composer install --no-dev
  - composer require codeclimate/php-test-reporter
cache:
  directories:
    - $HOME/.composer 
before_script:
  - cd tests
  - sh ./init_fuseki.sh
  - cd ..
after_script:
  - pkill -f 'java -Xmx1200M -jar'
  - vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"
addons:
  code_climate:
    repo_token: fb98170a5c7ea9cc2bbab19ff26268335e6a11a4f8267ca935e5e8ff4624886c
