
- name: Download Fuseki tarball
  get_url:
    url: https://archive.apache.org/dist/jena/binaries/apache-jena-fuseki-2.3.0.tar.gz
    dest: /home/vagrant/
    mode: 755

- name: Extract Fuseki to opt/
  command: chdir=/opt /bin/tar xzf /home/vagrant/apache-jena-fuseki-2.3.0.tar.gz
  args:
    warn: false

- name: Create a symbolic link to /opt/fuseki
  file:
    src: /opt/apache-jena-fuseki-2.3.0
    dest: /opt/fuseki
    state: link

- name: Add a new user fuseki
  user:
   name: fuseki
   home: /opt/fuseki
   system: yes
   create_home: no

- name: Create directories to /var/lib
  file:
    path: "/var/lib/fuseki/{{ item }}"
    state: directory
    owner: fuseki
    group: fuseki
    mode: 0775
  with_items:
    - backups
    - databases
    - system
    - system_files

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: fuseki
    group: fuseki
    mode: 0775
  with_items:
    - /var/log/fuseki
    - /etc/fuseki

- name: Link fuseki home
  file:
    src: "/var/lib/fuseki/{{ item }}"
    dest: /etc/fuseki/{{ item }}
    state: link
  with_items:
    - backups
    - databases
    - system
    - system_files

- name: Link logs to /etc/fuseki/logs
  file:
    src: /var/log/fuseki
    dest: /etc/fuseki/logs
    state: link

- name: Copy Fuseki config
  copy:
    src: files/fuseki
    dest: /etc/default/

# - name: Setup autostart
#   file:
#     src: /opt/fuseki/fuseki
#     dest: /etc/init.d/
#     state: link

- name: Setup autostart
  command: chdir=/etc/init.d ln -s /opt/fuseki/fuseki .
  args:
    warn: false
  ignore_errors: yes

- name: Update services
  command: update-rc.d fuseki defaults

- name: Start service Fuseki
  service:
    name: fuseki
    state: started

# - name: Start Fuseki Service
#   command: service fuseki start && update-rc.d fuseki defaults
