name: CI

on: [push, pull_request, workflow_dispatch]

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    timeout-minutes: 10
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php_version: ["7.2", "7.3", "7.4", "8.0"]
        experimental: [false]
        include:
          - php_version: "8.1"
            experimental: true

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Cache Composer dependencies
      uses: actions/cache@v2
      with:
        path: |
          /tmp/composer-cache
          vendor
          components
        key: ${{ runner.os }}-php${{ matrix.php_version}}-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-php${{ matrix.php_version}}-

    - name: Install Composer dependencies
      uses: php-actions/composer@v5
      with:
        php_version: ${{ matrix.php_version }}
        php_extensions: gettext intl xsl pcov

    - name: Run PHPUnit tests
      uses: php-actions/phpunit@v3
      env:
        LANGUAGE: fr
      with:
        version: 8.5
        php_version: ${{ matrix.php_version }}
        php_extensions: gettext intl xsl pcov
        memory_limit: 512M
        configuration: phpunit.xml
